{"name": "test_InvalidUserLogin", "status": "passed", "description": "Login with invalid 'USER' credentials", "attachments": [{"name": "Invalid Credentials", "source": "b0ba441b-bc54-4bde-9b45-e5c937c0ceea-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "96048fed-8273-4622-b9f0-ac5bf5f6f3c1-attachment.txt", "type": "text/plain"}], "start": 1740723780882, "stop": 1740723783144, "uuid": "cea47e15-7637-454b-b4db-29b77875962c", "historyId": "63bbb2b35c3a6026b2202e63a98de1bc", "testCaseId": "63bbb2b35c3a6026b2202e63a98de1bc", "fullName": "test_Login#test_InvalidUserLogin", "labels": [{"name": "severity", "value": "NORMAL"}, {"name": "suite", "value": "test_Login"}, {"name": "host", "value": "DESKTOP-4U48RM4"}, {"name": "thread", "value": "31580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Login"}]}